### ISSUE TITLE
count in any_xxx works

### ISSUE THREAD

**Issue by Persepheus** [tboby/cwtools-stellaris-config#238]
but cwtools tells me, its an error

**Comment by Goldziher** [comment]
does this work only with stuff like any_owned_xxx or any_controlled_xxx, or does it work as well with general stuff like any_ship or any_war? 

anyhow, i suggest you make the changes here and submit as pull request: 
https://github.com/tboby/cwtools-stellaris-config/blob/master/config/triggers.cwt

**Comment by Persepheus** [comment]
Well, I guess it works simply always, but I would have to test to be sure and I will not have time for it, sry.

**Comment by Goldziher** [comment]
So its confirmed. Can you add:

##cardinality = 0..1
count = int

To all any_ triggers?

**Comment by Persepheus** [comment]
yes

**Comment by Persepheus** [comment]
done

**Comment by Goldziher** [comment]
Great 😃

**Comment by tboby** [comment]
Done
