### ISSUE TITLE
controller in starbase scope works

### ISSUE THREAD

**Issue by Persepheus** [tboby/cwtools-stellaris-config#239]
(and is important!) but cwtools tells me, its an error

**Comment by Goldziher** [comment]
Again, example code

**Comment by Goldziher** [comment]
you mean controller = { } scope?

**Comment by Persepheus** [comment]
`find_random_system = {
                    trigger = {
                        id = attack.10.trigger.1
                        NOT = {
                            is_same_value = root.solar_system
                        }
                        exists = starbase 
                        or = {
                            starbase = {
                                exists = controller 
                                controller = {
                                    is_at_war_with = root.owner
                                }
                            }`
if a starbase is switched, its still owner of original owner, but controller switched

**Comment by Goldziher** [comment]
I see, yes this needs to be added.

**Comment by Goldziher** [comment]
You can close the issue, it was adddd
