### ISSUE TITLE
tile_potential in buildable_pops works

### ISSUE THREAD

**Issue by Persepheus** [tboby/cwtools-stellaris-config#240]
but cwtools tells me, its an error

**Comment by Goldziher** [comment]
Can you add example code?

**Comment by Persepheus** [comment]
buildable_lich_pop = {
	cost = {
		influence = 600
		energy = 5000
		minerals = 5000
	}

	potential_build = {
		has_ethic = ethic_fanatic_militarist
		has_ascension_perk = ap_lich
	}
	
	tile_potential  = {
		exists = planet
		planet = {
			count_pops = { limit = { is_species = buildable_lich_pop } count < 1 }
		}
	}
	
	species = {
		name = "lich"
		name_list = "AI"
		class = "DEAD"
		portrait = "default_robot"
		traits = {
			trait = "trait_lich"
		}
		new_pop_resource_requirement = {
			type = lich_food 
			value = 72.0
		}
		pops_auto_growth = 1.0

		pops_can_be_colonizers = no
		pops_can_migrate = no
		pops_can_reproduce = no
		pops_can_join_factions = no
		pop_maintenance = 0
		pops_can_be_slaves = no
		can_generate_leaders = no
		pops_have_happiness = no
		consumer_goods = no
		pop_ethics = no
		
	}
}

**Comment by Goldziher** [comment]
ok, i added a pull request with this

**Comment by Goldziher** [comment]
can also close this one
