### ISSUE TITLE
spawn_planet works with size random

### ISSUE THREAD

**Issue by Persepheus** [tboby/cwtools-stellaris-config#243]
but cwtools expects only float

spawn_planet = {
			class = "rl_habitable_normal" #"pc_ringworld_habitable"
			location = fromfrom.planet
			orbit_location = yes
			orbit_angle_offset = 45
			orbit_distance_offset = 12
			size = random
			has_ring = no
			
			init_effect = {

**Comment by Goldziher** [comment]
added this in a pull request (alongside other stuff): https://github.com/tboby/cwtools-stellaris-config/pull/247/files#diff-dded765ee29fa09080ea202822d9a966

**Comment by Goldziher** [comment]
Can you add a pull request?

Just edit effects.cwt, find spawn_ship and add:

##cardinality = 0..1
size = random

**Comment by Goldziher** [comment]
You can close the issue
