### ISSUE TITLE
List of missing elements and bugs

### ISSUE THREAD

**Issue by Goldziher** [tboby/cwtools-stellaris-config#84]
1. add the following scopes/targets: system_star, observation_outpost_owner, closest_system  
2. add firing scopeless events using country_event, planet_event etc. - this currently gives a false bug report.
3. owner_main_species not recognized as target
4. add ambient object as possible target for location and set_location. Also - see the vanilla event diplomatic.19, which sets location to "music_listening_planet"
5. if an event is set to hidden = yes and it has picture =, desc =, title =, location = etc... this currently gives an unexpected node message. This should be changed into a yellow notification along the lines of "event set to hidden, desc, title and picture are not displayed." same of course for options and the like. These do not give an error message and are not strictly speaking bugs, they can be redundant code or event that are either temporarily or permanently changed from one type to another but keep functioning (sub optimal of course, but still).
6. if an event is not defined as diplomatic but it has custom_gui defined for it, a yellow notification should be given rather than an error message.
7. CW999 should be removed. This notification was set for version 2.0.2, and this is no longer relevant. If it is it should be a blue notification. 
8. numerous errors in vanilla indicate the country is not defined as a viable target for effects that check species in cwtools, but it is a viable target and has a species. So this should be updated. This also applies to ship - but the check there should be whether the ship is shipclass_colonizer or not (otherwise it doesn't have species = xyz }
9. capital_scope can be used in solar_system scope. This should be added. 
10. when a new species archetype is defined the game auto-generates modifiers for this archetype. These require localisation. Currently cwtools doesn't recognize or expect these modifiers, leading to errors messages. Example modifeirs from STNH:

	BIOLOGICAL_species_trait_points_add #this is the only vanilla one here!
	HUMANOID_species_trait_points_add
	CHANGELING_species_trait_points_add
	CRYSTALINE_species_trait_points_add
	SILICOID_species_trait_points_add
	FLUIDIC_species_trait_points_add
	INSECTOID_species_trait_points_add
	AQUATIC_species_trait_points_add
	CYBORG_species_trait_points_add
11. It appears that some solar system initializers do not have galactic_object as root but rather country. The primary.example are the vanilla fallen empire solar system initializers. This needs to be worked out.
12. When new ethics are added, the game auto-generates modifiers for these in the form of pop_<key>_attraction_mult. Example: pop_ethic_egalitarian_attraction_mult. CWtools currently doesnt expect this.

**Comment by CaligulaCaesar** [comment]
Looks like referring to scope = nothing doesn't flag up an error when it should with scope[country] required.

**Comment by peerawatz** [comment]
Soundoverride/soundeffectoveride can only be used on existing sounds. As they essentially overrides any original sound used by the base game. This means that when you want to create advisor pack that will feature a lot of additional lines, normal "sound" function is used in place of "soundoverride".

You can look into sound/gui/gui_sound_effects.asset to see what advisor sounds are in the base game, and what must be added on top of it instead of override.

**Comment by CaligulaCaesar** [comment]
Closest system is usually a target for an effect (all but about 2 cases in Vanilla). It is sometimes used as a trigger, but when I tried this I couldn't get it to work, so I am not sure it actually does.

**Comment by Goldziher** [comment]
''Is system_star still needed now that we have star? ''

Yes, this is a shortcut to random_system_planet = { is_star = yes}, and with the 2.1 addition of multiple stars it scopes to the main system star.

**Comment by Goldziher** [comment]
Also - closest system is a target, and it is heavily used in fleet actions, alongside closest system etc.
